/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMysteryBoxV1Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "boxesShuffled"
      | "canMint"
      | "currency"
      | "entropyRequest"
      | "entropyRequestId"
      | "entropyRequested"
      | "getBoxResult"
      | "getCurrentMintPhase"
      | "initialize"
      | "initialized"
      | "mint"
      | "paymentRecipient"
      | "price"
      | "privateMintOpenTime"
      | "publicMintOpenTime"
      | "randomDataValue"
      | "remainingSupply"
      | "results"
      | "setMintTimes"
      | "setWhitelistStatus"
      | "setWhitelistStatusBatch"
      | "shuffleBoxes"
      | "totalMinted"
      | "totalSupply"
      | "whitelist"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BoxInitialized"
      | "BoxMinted"
      | "BoxesShuffled"
      | "EntropyReceived"
      | "EntropyRequested"
      | "MintTimesUpdated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "boxesShuffled",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "canMint",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "currency", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "entropyRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequestId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBoxResult",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMintPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      BigNumberish,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialized",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "mint", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "paymentRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "privateMintOpenTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "publicMintOpenTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "randomDataValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "remainingSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "results",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMintTimes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistStatus",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setWhitelistStatusBatch",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "shuffleBoxes",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMinted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "whitelist",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "boxesShuffled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canMint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "currency", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequestId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBoxResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMintPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "privateMintOpenTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "publicMintOpenTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "randomDataValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remainingSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "results", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMintTimes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setWhitelistStatusBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "shuffleBoxes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "whitelist", data: BytesLike): Result;
}

export namespace BoxInitializedEvent {
  export type InputTuple = [
    name: string,
    symbol: string,
    totalSupply: BigNumberish,
    price: BigNumberish,
    currency: AddressLike,
    paymentRecipient: AddressLike,
    privateMintOpenTime: BigNumberish,
    publicMintOpenTime: BigNumberish
  ];
  export type OutputTuple = [
    name: string,
    symbol: string,
    totalSupply: bigint,
    price: bigint,
    currency: string,
    paymentRecipient: string,
    privateMintOpenTime: bigint,
    publicMintOpenTime: bigint
  ];
  export interface OutputObject {
    name: string;
    symbol: string;
    totalSupply: bigint;
    price: bigint;
    currency: string;
    paymentRecipient: string;
    privateMintOpenTime: bigint;
    publicMintOpenTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BoxMintedEvent {
  export type InputTuple = [
    payer: AddressLike,
    minter: AddressLike,
    tokenId: BigNumberish
  ];
  export type OutputTuple = [payer: string, minter: string, tokenId: bigint];
  export interface OutputObject {
    payer: string;
    minter: string;
    tokenId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BoxesShuffledEvent {
  export type InputTuple = [shuffledNumbers: BigNumberish[]];
  export type OutputTuple = [shuffledNumbers: bigint[]];
  export interface OutputObject {
    shuffledNumbers: bigint[];
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyReceivedEvent {
  export type InputTuple = [
    sequenceNumber: BigNumberish,
    provider: AddressLike,
    randomData: BytesLike
  ];
  export type OutputTuple = [
    sequenceNumber: bigint,
    provider: string,
    randomData: string
  ];
  export interface OutputObject {
    sequenceNumber: bigint;
    provider: string;
    randomData: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish];
  export type OutputTuple = [requestId: bigint];
  export interface OutputObject {
    requestId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintTimesUpdatedEvent {
  export type InputTuple = [
    privateMintOpenTime: BigNumberish,
    publicMintOpenTime: BigNumberish
  ];
  export type OutputTuple = [
    privateMintOpenTime: bigint,
    publicMintOpenTime: bigint
  ];
  export interface OutputObject {
    privateMintOpenTime: bigint;
    publicMintOpenTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [account: AddressLike, status: boolean];
  export type OutputTuple = [account: string, status: boolean];
  export interface OutputObject {
    account: string;
    status: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IMysteryBoxV1 extends BaseContract {
  connect(runner?: ContractRunner | null): IMysteryBoxV1;
  waitForDeployment(): Promise<this>;

  interface: IMysteryBoxV1Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  boxesShuffled: TypedContractMethod<[], [boolean], "view">;

  canMint: TypedContractMethod<[minter: AddressLike], [boolean], "view">;

  currency: TypedContractMethod<[], [string], "view">;

  entropyRequest: TypedContractMethod<[seed: BytesLike], [void], "payable">;

  entropyRequestId: TypedContractMethod<[], [bigint], "view">;

  entropyRequested: TypedContractMethod<[], [boolean], "view">;

  getBoxResult: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getCurrentMintPhase: TypedContractMethod<[], [string], "view">;

  initialize: TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _price: BigNumberish,
      _currency: AddressLike,
      _paymentRecipient: AddressLike,
      _privateMintOpenTime: BigNumberish,
      _publicMintOpenTime: BigNumberish,
      _pythEntropy: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  initialized: TypedContractMethod<[], [boolean], "view">;

  mint: TypedContractMethod<[minter: AddressLike], [void], "nonpayable">;

  paymentRecipient: TypedContractMethod<[], [string], "view">;

  price: TypedContractMethod<[], [bigint], "view">;

  privateMintOpenTime: TypedContractMethod<[], [bigint], "view">;

  publicMintOpenTime: TypedContractMethod<[], [bigint], "view">;

  randomDataValue: TypedContractMethod<[], [bigint], "view">;

  remainingSupply: TypedContractMethod<[], [bigint], "view">;

  results: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  setMintTimes: TypedContractMethod<
    [_privateMintOpenTime: BigNumberish, _publicMintOpenTime: BigNumberish],
    [void],
    "nonpayable"
  >;

  setWhitelistStatus: TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;

  setWhitelistStatusBatch: TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;

  shuffleBoxes: TypedContractMethod<[], [void], "nonpayable">;

  totalMinted: TypedContractMethod<[], [bigint], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  whitelist: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "boxesShuffled"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "canMint"
  ): TypedContractMethod<[minter: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "currency"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequest"
  ): TypedContractMethod<[seed: BytesLike], [void], "payable">;
  getFunction(
    nameOrSignature: "entropyRequestId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "entropyRequested"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "getBoxResult"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentMintPhase"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _totalSupply: BigNumberish,
      _price: BigNumberish,
      _currency: AddressLike,
      _paymentRecipient: AddressLike,
      _privateMintOpenTime: BigNumberish,
      _publicMintOpenTime: BigNumberish,
      _pythEntropy: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialized"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<[minter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paymentRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "privateMintOpenTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "publicMintOpenTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "randomDataValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "remainingSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "results"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "setMintTimes"
  ): TypedContractMethod<
    [_privateMintOpenTime: BigNumberish, _publicMintOpenTime: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWhitelistStatus"
  ): TypedContractMethod<
    [account: AddressLike, status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setWhitelistStatusBatch"
  ): TypedContractMethod<
    [accounts: AddressLike[], status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "shuffleBoxes"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalMinted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "whitelist"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;

  getEvent(
    key: "BoxInitialized"
  ): TypedContractEvent<
    BoxInitializedEvent.InputTuple,
    BoxInitializedEvent.OutputTuple,
    BoxInitializedEvent.OutputObject
  >;
  getEvent(
    key: "BoxMinted"
  ): TypedContractEvent<
    BoxMintedEvent.InputTuple,
    BoxMintedEvent.OutputTuple,
    BoxMintedEvent.OutputObject
  >;
  getEvent(
    key: "BoxesShuffled"
  ): TypedContractEvent<
    BoxesShuffledEvent.InputTuple,
    BoxesShuffledEvent.OutputTuple,
    BoxesShuffledEvent.OutputObject
  >;
  getEvent(
    key: "EntropyReceived"
  ): TypedContractEvent<
    EntropyReceivedEvent.InputTuple,
    EntropyReceivedEvent.OutputTuple,
    EntropyReceivedEvent.OutputObject
  >;
  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "MintTimesUpdated"
  ): TypedContractEvent<
    MintTimesUpdatedEvent.InputTuple,
    MintTimesUpdatedEvent.OutputTuple,
    MintTimesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "BoxInitialized(string,string,uint256,uint256,address,address,uint256,uint256)": TypedContractEvent<
      BoxInitializedEvent.InputTuple,
      BoxInitializedEvent.OutputTuple,
      BoxInitializedEvent.OutputObject
    >;
    BoxInitialized: TypedContractEvent<
      BoxInitializedEvent.InputTuple,
      BoxInitializedEvent.OutputTuple,
      BoxInitializedEvent.OutputObject
    >;

    "BoxMinted(address,address,uint256)": TypedContractEvent<
      BoxMintedEvent.InputTuple,
      BoxMintedEvent.OutputTuple,
      BoxMintedEvent.OutputObject
    >;
    BoxMinted: TypedContractEvent<
      BoxMintedEvent.InputTuple,
      BoxMintedEvent.OutputTuple,
      BoxMintedEvent.OutputObject
    >;

    "BoxesShuffled(uint256[])": TypedContractEvent<
      BoxesShuffledEvent.InputTuple,
      BoxesShuffledEvent.OutputTuple,
      BoxesShuffledEvent.OutputObject
    >;
    BoxesShuffled: TypedContractEvent<
      BoxesShuffledEvent.InputTuple,
      BoxesShuffledEvent.OutputTuple,
      BoxesShuffledEvent.OutputObject
    >;

    "EntropyReceived(uint64,address,bytes32)": TypedContractEvent<
      EntropyReceivedEvent.InputTuple,
      EntropyReceivedEvent.OutputTuple,
      EntropyReceivedEvent.OutputObject
    >;
    EntropyReceived: TypedContractEvent<
      EntropyReceivedEvent.InputTuple,
      EntropyReceivedEvent.OutputTuple,
      EntropyReceivedEvent.OutputObject
    >;

    "EntropyRequested(uint64)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "MintTimesUpdated(uint256,uint256)": TypedContractEvent<
      MintTimesUpdatedEvent.InputTuple,
      MintTimesUpdatedEvent.OutputTuple,
      MintTimesUpdatedEvent.OutputObject
    >;
    MintTimesUpdated: TypedContractEvent<
      MintTimesUpdatedEvent.InputTuple,
      MintTimesUpdatedEvent.OutputTuple,
      MintTimesUpdatedEvent.OutputObject
    >;

    "WhitelistUpdated(address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
