/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMysteryBoxV1Sol from "./IMysteryBoxV1.sol";
export type { iMysteryBoxV1Sol };
export type { IMysteryBoxRegistry } from "./IMysteryBoxRegistry";
export type { MysteryBoxRegistry } from "./MysteryBoxRegistry";
export type { MysteryBoxV1 } from "./MysteryBoxV1";
export type { MysteryBoxV2 } from "./MysteryBoxV2";
