/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMysteryBoxRegistry,
  IMysteryBoxRegistryInterface,
} from "../../../contracts/mystery-boxes/IMysteryBoxRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "boxContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "paymentRecipient",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "privateMintOpenTime",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "publicMintOpenTime",
        type: "uint256",
      },
    ],
    name: "BoxInitialized",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "boxContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "bool",
        name: "isRegistered",
        type: "bool",
      },
    ],
    name: "BoxRegistered",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "boxContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "minter",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "prizeCollection",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "prizeTokenId",
        type: "uint256",
      },
    ],
    name: "BoxRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "boxContract",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "address",
        name: "minter",
        type: "address",
      },
    ],
    name: "BoxTracked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "minter",
        type: "address",
      },
    ],
    name: "trackBox",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "totalSupply",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "price",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "currency",
        type: "address",
      },
      {
        internalType: "address",
        name: "paymentRecipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "privateMintOpenTime",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "publicMintOpenTime",
        type: "uint256",
      },
    ],
    name: "trackBoxParameters",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "minter",
        type: "address",
      },
      {
        internalType: "address",
        name: "prizeCollection",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "prizeTokenId",
        type: "uint256",
      },
    ],
    name: "trackBoxReveal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMysteryBoxRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IMysteryBoxRegistryInterface {
    return new Interface(_abi) as IMysteryBoxRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMysteryBoxRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IMysteryBoxRegistry;
  }
}
