/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type CollateralStruct = {
  criteria: BigNumberish;
  collection: AddressLike;
  identifier: BigNumberish;
};

export type CollateralStructOutput = [
  criteria: bigint,
  collection: string,
  identifier: bigint
] & { criteria: bigint; collection: string; identifier: bigint };

export type MarketOfferTermsStruct = {
  currency: AddressLike;
  amount: BigNumberish;
};

export type MarketOfferTermsStructOutput = [
  currency: string,
  amount: bigint
] & { currency: string; amount: bigint };

export type FeeTermsStruct = { recipient: AddressLike; rate: BigNumberish };

export type FeeTermsStructOutput = [recipient: string, rate: bigint] & {
  recipient: string;
  rate: bigint;
};

export type MarketOfferStruct = {
  side: BigNumberish;
  maker: AddressLike;
  taker: AddressLike;
  collateral: CollateralStruct;
  terms: MarketOfferTermsStruct;
  fee: FeeTermsStruct;
  expiration: BigNumberish;
  salt: BigNumberish;
};

export type MarketOfferStructOutput = [
  side: bigint,
  maker: string,
  taker: string,
  collateral: CollateralStructOutput,
  terms: MarketOfferTermsStructOutput,
  fee: FeeTermsStructOutput,
  expiration: bigint,
  salt: bigint
] & {
  side: bigint;
  maker: string;
  taker: string;
  collateral: CollateralStructOutput;
  terms: MarketOfferTermsStructOutput;
  fee: FeeTermsStructOutput;
  expiration: bigint;
  salt: bigint;
};

export type RedemptionChargeStruct = {
  redeemer: AddressLike;
  collection: AddressLike;
  tokenId: BigNumberish;
  currency: AddressLike;
  amount: BigNumberish;
  expiration: BigNumberish;
  salt: BigNumberish;
};

export type RedemptionChargeStructOutput = [
  redeemer: string,
  collection: string,
  tokenId: bigint,
  currency: string,
  amount: bigint,
  expiration: bigint,
  salt: bigint
] & {
  redeemer: string;
  collection: string;
  tokenId: bigint;
  currency: string;
  amount: bigint;
  expiration: bigint;
  salt: bigint;
};

export interface IKettleMarketplaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelOffers"
      | "incrementNonce"
      | "redeem"
      | "takeAsk"
      | "takeBid"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MarketOfferTaken"
      | "NonceIncremented"
      | "OfferCancelled"
      | "OfferManagerUpdated"
      | "Redemption"
      | "RedemptionSignerUpdated"
      | "RedemptionWalletUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelOffers",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "incrementNonce",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [RedemptionChargeStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "takeAsk",
    values: [AddressLike, MarketOfferStruct, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "takeBid",
    values: [BigNumberish, MarketOfferStruct, BytesLike, BytesLike[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelOffers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "incrementNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "takeAsk", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "takeBid", data: BytesLike): Result;
}

export namespace MarketOfferTakenEvent {
  export type InputTuple = [
    hash: BytesLike,
    tokenId: BigNumberish,
    taker: AddressLike,
    offer: MarketOfferStruct
  ];
  export type OutputTuple = [
    hash: string,
    tokenId: bigint,
    taker: string,
    offer: MarketOfferStructOutput
  ];
  export interface OutputObject {
    hash: string;
    tokenId: bigint;
    taker: string;
    offer: MarketOfferStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NonceIncrementedEvent {
  export type InputTuple = [
    operator: AddressLike,
    user: AddressLike,
    nonce: BigNumberish
  ];
  export type OutputTuple = [operator: string, user: string, nonce: bigint];
  export interface OutputObject {
    operator: string;
    user: string;
    nonce: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferCancelledEvent {
  export type InputTuple = [
    operator: AddressLike,
    user: AddressLike,
    salt: BigNumberish
  ];
  export type OutputTuple = [operator: string, user: string, salt: bigint];
  export interface OutputObject {
    operator: string;
    user: string;
    salt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OfferManagerUpdatedEvent {
  export type InputTuple = [manager: AddressLike];
  export type OutputTuple = [manager: string];
  export interface OutputObject {
    manager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionEvent {
  export type InputTuple = [hash: BytesLike, charge: RedemptionChargeStruct];
  export type OutputTuple = [
    hash: string,
    charge: RedemptionChargeStructOutput
  ];
  export interface OutputObject {
    hash: string;
    charge: RedemptionChargeStructOutput;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionSignerUpdatedEvent {
  export type InputTuple = [signer: AddressLike];
  export type OutputTuple = [signer: string];
  export interface OutputObject {
    signer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RedemptionWalletUpdatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IKettleMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): IKettleMarketplace;
  waitForDeployment(): Promise<this>;

  interface: IKettleMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelOffers: TypedContractMethod<
    [salts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  incrementNonce: TypedContractMethod<[], [void], "nonpayable">;

  redeem: TypedContractMethod<
    [charge: RedemptionChargeStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;

  takeAsk: TypedContractMethod<
    [taker: AddressLike, offer: MarketOfferStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;

  takeBid: TypedContractMethod<
    [
      tokenId: BigNumberish,
      offer: MarketOfferStruct,
      signature: BytesLike,
      proof: BytesLike[]
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelOffers"
  ): TypedContractMethod<[salts: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "incrementNonce"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [charge: RedemptionChargeStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "takeAsk"
  ): TypedContractMethod<
    [taker: AddressLike, offer: MarketOfferStruct, signature: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "takeBid"
  ): TypedContractMethod<
    [
      tokenId: BigNumberish,
      offer: MarketOfferStruct,
      signature: BytesLike,
      proof: BytesLike[]
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "MarketOfferTaken"
  ): TypedContractEvent<
    MarketOfferTakenEvent.InputTuple,
    MarketOfferTakenEvent.OutputTuple,
    MarketOfferTakenEvent.OutputObject
  >;
  getEvent(
    key: "NonceIncremented"
  ): TypedContractEvent<
    NonceIncrementedEvent.InputTuple,
    NonceIncrementedEvent.OutputTuple,
    NonceIncrementedEvent.OutputObject
  >;
  getEvent(
    key: "OfferCancelled"
  ): TypedContractEvent<
    OfferCancelledEvent.InputTuple,
    OfferCancelledEvent.OutputTuple,
    OfferCancelledEvent.OutputObject
  >;
  getEvent(
    key: "OfferManagerUpdated"
  ): TypedContractEvent<
    OfferManagerUpdatedEvent.InputTuple,
    OfferManagerUpdatedEvent.OutputTuple,
    OfferManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Redemption"
  ): TypedContractEvent<
    RedemptionEvent.InputTuple,
    RedemptionEvent.OutputTuple,
    RedemptionEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionSignerUpdated"
  ): TypedContractEvent<
    RedemptionSignerUpdatedEvent.InputTuple,
    RedemptionSignerUpdatedEvent.OutputTuple,
    RedemptionSignerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RedemptionWalletUpdated"
  ): TypedContractEvent<
    RedemptionWalletUpdatedEvent.InputTuple,
    RedemptionWalletUpdatedEvent.OutputTuple,
    RedemptionWalletUpdatedEvent.OutputObject
  >;

  filters: {
    "MarketOfferTaken(bytes32,uint256,address,tuple)": TypedContractEvent<
      MarketOfferTakenEvent.InputTuple,
      MarketOfferTakenEvent.OutputTuple,
      MarketOfferTakenEvent.OutputObject
    >;
    MarketOfferTaken: TypedContractEvent<
      MarketOfferTakenEvent.InputTuple,
      MarketOfferTakenEvent.OutputTuple,
      MarketOfferTakenEvent.OutputObject
    >;

    "NonceIncremented(address,address,uint256)": TypedContractEvent<
      NonceIncrementedEvent.InputTuple,
      NonceIncrementedEvent.OutputTuple,
      NonceIncrementedEvent.OutputObject
    >;
    NonceIncremented: TypedContractEvent<
      NonceIncrementedEvent.InputTuple,
      NonceIncrementedEvent.OutputTuple,
      NonceIncrementedEvent.OutputObject
    >;

    "OfferCancelled(address,address,uint256)": TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;
    OfferCancelled: TypedContractEvent<
      OfferCancelledEvent.InputTuple,
      OfferCancelledEvent.OutputTuple,
      OfferCancelledEvent.OutputObject
    >;

    "OfferManagerUpdated(address)": TypedContractEvent<
      OfferManagerUpdatedEvent.InputTuple,
      OfferManagerUpdatedEvent.OutputTuple,
      OfferManagerUpdatedEvent.OutputObject
    >;
    OfferManagerUpdated: TypedContractEvent<
      OfferManagerUpdatedEvent.InputTuple,
      OfferManagerUpdatedEvent.OutputTuple,
      OfferManagerUpdatedEvent.OutputObject
    >;

    "Redemption(bytes32,tuple)": TypedContractEvent<
      RedemptionEvent.InputTuple,
      RedemptionEvent.OutputTuple,
      RedemptionEvent.OutputObject
    >;
    Redemption: TypedContractEvent<
      RedemptionEvent.InputTuple,
      RedemptionEvent.OutputTuple,
      RedemptionEvent.OutputObject
    >;

    "RedemptionSignerUpdated(address)": TypedContractEvent<
      RedemptionSignerUpdatedEvent.InputTuple,
      RedemptionSignerUpdatedEvent.OutputTuple,
      RedemptionSignerUpdatedEvent.OutputObject
    >;
    RedemptionSignerUpdated: TypedContractEvent<
      RedemptionSignerUpdatedEvent.InputTuple,
      RedemptionSignerUpdatedEvent.OutputTuple,
      RedemptionSignerUpdatedEvent.OutputObject
    >;

    "RedemptionWalletUpdated(address)": TypedContractEvent<
      RedemptionWalletUpdatedEvent.InputTuple,
      RedemptionWalletUpdatedEvent.OutputTuple,
      RedemptionWalletUpdatedEvent.OutputObject
    >;
    RedemptionWalletUpdated: TypedContractEvent<
      RedemptionWalletUpdatedEvent.InputTuple,
      RedemptionWalletUpdatedEvent.OutputTuple,
      RedemptionWalletUpdatedEvent.OutputObject
    >;
  };
}
