/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IKettleAssetFactory } from "./IKettleAssetFactory";
export type { IMysteryBoxV1 } from "./IMysteryBoxV1";
