/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IKettleAssetFactory,
  IKettleAssetFactoryInterface,
} from "../../../../contracts/mystery-boxes/IMysteryBoxV1.sol/IKettleAssetFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "asset",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "id",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IKettleAssetFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IKettleAssetFactoryInterface {
    return new Interface(_abi) as IKettleAssetFactoryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IKettleAssetFactory {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IKettleAssetFactory;
  }
}
